import React from 'react';

import { CallToAction, Flex, Heading, Text } from '@labs/components';

import styles from './resume-analysis.module.scss';

export const ResumeAnalysis = () => {
	return (
		<div className={styles.ResumeAnalysis}>
			<Flex.Column gap={6}>
				<Flex alignItems="center" gap={12}>
					<Heading.h3 weight={400} animate="slide">
						Resume Analysis
					</Heading.h3>
				</Flex>

				<Text color="var(--text-gray)" animate="fade" className="mb-[40px]">
					A breakdown of how your resume can be better
				</Text>
			</Flex.Column>
			<Flex.Row gap={32} className={styles.ResumeAnalysisSection}>
				<aside className={styles.ResumeAnalysisAside}>
					<div className={styles.ResumeAnalysisBox}></div>
				</aside>
				<Flex.Column gap={24} className={styles.ResumeAnalysisMain}>
					<Flex.Column gap={14} className={styles.ResumeAnalysisBox}>
						<Heading.h4 weight={500} animate="slide">
							Your resume could be improved!
						</Heading.h4>
						<Text color="var(--text-gray)" animate="fade">
							A general summary note on how the resume can be improved. Could be
							generated by AI to make it unique per different user.
						</Text>
						<CallToAction className="mt-[10px]">Build Resume</CallToAction>
					</Flex.Column>
					<Flex.Column gap={12}>
						<Heading.h5 weight={600} animate="slide">
							Analysis
						</Heading.h5>
						<div className={styles.ResumeAnalysisBox}></div>
					</Flex.Column>
				</Flex.Column>
			</Flex.Row>
		</div>
	);
};
