// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next';

const skills = [
	'Programming',
	'Software Development',
	'Python',
	'Web Development',
	'Frontend Development',
	'Backend Development',
	'Full Stack Development',
	'HTML',
	'CSS',
	'JavaScript',
	'TypeScript',
	'React',
	'Angular',
	'Svelte',
	'Mobile App Development',
	'Swift',
	'Java',
	'C++',
	'C#',
	'Ruby',
	'PHP',
	'Node.js',
	'React Native',
	'Flutter',
	'Ionic',
	'Angular',
	'Vue.js',
	'Express.js',
	'Django',
	'Flask',
	'Ruby on Rails',
	'ASP.NET',
	'Unity',
	'Database Management',
	'MongoDB',
	'SQL',
	'Cybersecurity',
	'Encryption',
	'Ethical Hacking',
	'Machine Learning/AI',
	'TensorFlow',
	'PyTorch',
	'Cloud Computing',
	'Azure',
	'AWS',
	'GCP',
	'Docker',
	'Kubernetes',
	'Network Administration',
	'Data Analysis',
	'R',
	'MATLAB',
	'Graphic Design',
	'Illustrator',
	'Photoshop',

	'Communication',
	'Leadership',
	'Teamwork',
	'Problem Solving',
	'Time Management',
	'Critical Thinking',
	'Adaptability',
	'Creativity',
	'Work Ethic',
	'Emotional Intelligence',

	'Painting',
	'Drawing',
	'Sculpture',
	'Photography',
	'Creative Writing',
	'Dance',
	'Acting',
	'Musical Instrument Performance',
	'Singing',
	'Digital Art',

	'Carpentry',
	'Electrical Work',
	'Plumbing',
	'Welding',
	'Automotive Repair',
	'Masonry',
	'Landscaping',
	'Construction',
	'HVAC Maintenance',
	'Metalwork',

	'Project Management',
	'Financial Analysis',
	'Marketing',
	'Sales',
	'Human Resources',
	'Negotiation',
	'Entrepreneurship',
	'Supply Chain Management',
	'Customer Service',
	'Strategic Planning',

	'Research',
	'Writing',
	'Public Speaking',
	'Statistical Analysis',
	'Teaching',
	'Study Strategies',
	'Language Proficiency (English, Spanish, etc.)',
	'Historical Analysis',
	'Scientific Methodology',
	'Mathematical Reasoning',

	'Nutrition Planning',
	'Personal Fitness Training',
	'Yoga Instruction',
	'Meditation Techniques',
	'First Aid & CPR',
	'Mental Health First Aid',
	'Sports Coaching',
	'Physical Therapy Techniques',
	'Holistic Health Practices',
	'Personal Wellness Planning',

	'Camping',
	'Hiking',
	'Fishing',
	'Hunting',
	'Navigation (Map Reading, GPS, etc.)',
	'Wilderness Survival',
	'First Aid in Wilderness',
	'Foraging',
	'Water Purification',
	'Knot Tying',

	'Cooking',
	'Baking',
	'Gardening',
	'Home Repair and Maintenance',
	'Sewing',
	'Knitting',
	'Pet Care',
	'Budgeting',
	'Interior Design',
	'Organization',

	'Video Production',
	'Podcasting',
	'Blogging',
	'Social Media Management',
	'SEO Optimization',
	'Content Creation',
	'Digital Marketing',
	'3D Modeling',
	'Animation',
	'Game Design',
];

export default function handler(
	req: NextApiRequest,
	res: NextApiResponse<string[]>
) {
	const { query } = req;

	if (query?.q) {
		const filteredSkills = skills.filter((skill) =>
			skill.toLowerCase().includes((query?.q as string)?.toLowerCase())
		);
		return res.status(200).json(filteredSkills);
	}

	return res.status(200).json(skills);
}
